# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c1f576c3d4f6a9287c7e10bb747c5ae56197f94fbc909f484b45e308bb2e565f9b2ae5240ca2dfc73fe547729d4ac6eaaa9c13c1599e95ad000d3dc0796234e

test:
  secret_key_base: 35ae31ae8d73c32e18bcf1e1e019917fe0a7a214349e9409113edc3994730234ffb614e67fa3f6365fa9f93310aba2917e4e1524ad5ee748c0e9d2838dde7264

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
